"""initial

Revision ID: 7517fedd4f86
Revises: 
Create Date: 2026-05-16 00:38:35.910119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7517fedd4f86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casillas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('casilla_id', sa.String(), nullable=False),
    sa.Column('entidad_federativa', sa.String(), nullable=False),
    sa.Column('municipio_o_delegacion', sa.String(), nullable=False),
    sa.Column('distrito', sa.String(), nullable=False),
    sa.Column('seccion', sa.String(), nullable=False),
    sa.Column('tipo_casilla', sa.String(), nullable=False),
    sa.Column('tipo_eleccion', sa.String(), nullable=False),
    sa.Column('proceso_electoral', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('casilla_id')
    )
    op.create_table('actas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('casilla_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('boletas_recibidas', sa.Integer(), nullable=True),
    sa.Column('BS', sa.Integer(), nullable=True),
    sa.Column('PV', sa.Integer(), nullable=True),
    sa.Column('RPPV', sa.Integer(), nullable=True),
    sa.Column('SV', sa.Integer(), nullable=True),
    sa.Column('BSU', sa.Integer(), nullable=True),
    sa.Column('CNR', sa.Integer(), nullable=True),
    sa.Column('VN', sa.Integer(), nullable=True),
    sa.Column('RV', sa.Integer(), nullable=True),
    sa.Column('criterio_1_pv_rppv_sv', sa.Boolean(), nullable=True),
    sa.Column('criterio_2_sv_bsu', sa.Boolean(), nullable=True),
    sa.Column('criterio_3_bsu_rv', sa.Boolean(), nullable=True),
    sa.Column('criterio_4_sum_vi_rv', sa.Boolean(), nullable=True),
    sa.Column('acta_consistente', sa.Boolean(), nullable=True),
    sa.Column('tipo_error', sa.String(), nullable=True),
    sa.Column('se_presentaron', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('hojas_de_incidentes', sa.Integer(), nullable=True),
    sa.Column('boletas_procesadas', sa.Integer(), nullable=True),
    sa.Column('boletas_revision_humana', sa.Integer(), nullable=True),
    sa.Column('hash_boletas', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['casilla_id'], ['casillas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boletas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('casilla_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('voto_detectado', sa.String(), nullable=True),
    sa.Column('confianza_ia', sa.Float(), nullable=True),
    sa.Column('revision_humana', sa.Boolean(), nullable=True),
    sa.Column('clasificacion_final', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['casilla_id'], ['casillas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('casilla_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('clave_de_elector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['casilla_id'], ['casillas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_de_elector')
    )
    op.create_table('eventos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entidad_tipo', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.String(), nullable=False),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inconsistencias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('boleta_id', sa.String(), nullable=False),
    sa.Column('tipo_inconsistencia', sa.String(), nullable=False),
    sa.Column('severidad', sa.String(), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=True),
    sa.Column('notas_resolucion', sa.String(), nullable=True),
    sa.Column('resuelta_por', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas.id'], ),
    sa.ForeignKeyConstraint(['resuelta_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('acta_id', sa.String(), nullable=False),
    sa.Column('partido_o_coalicion', sa.String(), nullable=False),
    sa.Column('partido_id', sa.String(), nullable=False),
    sa.Column('votos', sa.Integer(), nullable=True),
    sa.Column('es_coalicion', sa.Boolean(), nullable=True),
    sa.Column('partidos_coalicion', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acta_id'], ['actas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    op.drop_table('inconsistencias')
    op.drop_table('eventos')
    op.drop_table('usuarios')
    op.drop_table('boletas')
    op.drop_table('actas')
    op.drop_table('casillas')
    # ### end Alembic commands ###
