"""initial tables

Revision ID: 7dd04383681c
Revises: 
Create Date: 2026-05-15 14:45:37.967137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd04383681c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polling_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('polling_station_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('detected_vote', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewed_by_human', sa.Boolean(), nullable=True),
    sa.Column('final_classification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('polling_station_id', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tally_sheets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('polling_station_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('null_votes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('polling_station_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inconsistencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ballot_id', sa.String(), nullable=False),
    sa.Column('inconsistency_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inconsistencies')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('tally_sheets')
    op.drop_table('results')
    op.drop_table('ballots')
    op.drop_table('polling_stations')
    # ### end Alembic commands ###
